Update: Hello World
Adding the # comments inline in the `compile.hxml` file cause errors on launching debug if you just copied and pasted the snippet:-

```
Error: : unknown option '-debug				#'.
Did you mean:
  --debug   add debug information to the compiled code
```
Sources:
* https://heaps.io/documentation/hello-world.html